# Generated by Django 5.2.9 on 2025-12-30 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_memory_extraction_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=512)),
                ('change_type', models.CharField(choices=[('created', 'Created'), ('modified', 'Modified'), ('deleted', 'Deleted'), ('ai_revision', 'AI Revision')], max_length=32)),
                ('source', models.CharField(choices=[('user', 'User'), ('ai', 'AI'), ('system', 'System')], default='user', max_length=32)),
                ('diff_summary', models.TextField(blank=True)),
                ('change_reason', models.TextField(blank=True)),
                ('model_used', models.CharField(blank=True, max_length=128)),
                ('session_id', models.CharField(blank=True, max_length=128)),
                ('lines_added', models.IntegerField(default=0)),
                ('lines_removed', models.IntegerField(default=0)),
                ('lines_changed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('architecture', 'Architecture'), ('patterns', 'Patterns'), ('dependencies', 'Dependencies'), ('features', 'Features'), ('structure', 'Structure'), ('improvements', 'Improvements')], max_length=32)),
                ('memory_key', models.CharField(max_length=255)),
                ('memory_value', models.TextField()),
                ('related_files', models.JSONField(default=list)),
                ('importance', models.IntegerField(default=5)),
                ('confidence', models.FloatField(default=0.5)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('verification_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-importance', '-extracted_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=512)),
                ('file_name', models.CharField(max_length=255)),
                ('file_extension', models.CharField(blank=True, max_length=32)),
                ('content', models.TextField()),
                ('line_count', models.IntegerField(default=0)),
                ('language', models.CharField(blank=True, max_length=64)),
                ('sha256_hash', models.CharField(max_length=64)),
                ('indexed_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-indexed_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='aicapability',
            new_name='api_aicapab_domain_b91538_idx',
            old_name='api_aicapab_domain_prof_idx',
        ),
        migrations.RenameIndex(
            model_name='aiselfmemory',
            new_name='api_aiselfm_categor_12b9ed_idx',
            old_name='api_aiselfm_categor_5a7c8f_idx',
        ),
        migrations.RenameIndex(
            model_name='aiselfmemory',
            new_name='api_aiselfm_importa_f989d5_idx',
            old_name='api_aiselfm_importa_8b4e2a_idx',
        ),
        migrations.RenameIndex(
            model_name='chatsession',
            new_name='api_chatses_pinned_2d4e30_idx',
            old_name='api_chatses_pinned_7b1e4a_idx',
        ),
        migrations.RenameIndex(
            model_name='conversationmessage',
            new_name='api_convers_session_4f4fcb_idx',
            old_name='api_convers_session_1b74bb_idx',
        ),
        migrations.RenameIndex(
            model_name='conversationsummary',
            new_name='api_convers_user_id_84b6a3_idx',
            old_name='api_convers_user_id_j0k1l2_idx',
        ),
        migrations.RenameIndex(
            model_name='memoryspot',
            new_name='api_memorys_user_id_a3897a_idx',
            old_name='api_memorys_user_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='memoryspot',
            new_name='api_memorys_memory__5a44fd_idx',
            old_name='api_memorys_memory_t_status_idx',
        ),
        migrations.RenameIndex(
            model_name='memoryspot',
            new_name='api_memorys_session_be67a2_idx',
            old_name='api_memorys_session_idx',
        ),
        migrations.RenameIndex(
            model_name='userfact',
            new_name='api_userfac_user_id_b24c92_idx',
            old_name='api_userfac_user_id_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='userfact',
            new_name='api_userfac_fact_ty_3089dc_idx',
            old_name='api_userfac_fact_ty_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='userpreference',
            new_name='api_userpre_user_id_3fdf79_idx',
            old_name='api_userpre_user_id_g7h8i9_idx',
        ),
        migrations.AddIndex(
            model_name='codememory',
            index=models.Index(fields=['category'], name='api_codemem_categor_3ae2dd_idx'),
        ),
        migrations.AddIndex(
            model_name='codememory',
            index=models.Index(fields=['importance'], name='api_codemem_importa_549744_idx'),
        ),
        migrations.AddIndex(
            model_name='codememory',
            index=models.Index(fields=['extracted_at'], name='api_codemem_extract_786c9c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='codememory',
            unique_together={('category', 'memory_key')},
        ),
        migrations.AddIndex(
            model_name='codesnapshot',
            index=models.Index(fields=['file_path'], name='api_codesna_file_pa_4e334d_idx'),
        ),
        migrations.AddIndex(
            model_name='codesnapshot',
            index=models.Index(fields=['file_extension'], name='api_codesna_file_ex_ac8dfd_idx'),
        ),
        migrations.AddIndex(
            model_name='codesnapshot',
            index=models.Index(fields=['language'], name='api_codesna_languag_10f0ae_idx'),
        ),
        migrations.AddIndex(
            model_name='codesnapshot',
            index=models.Index(fields=['indexed_at'], name='api_codesna_indexed_f333c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='codesnapshot',
            unique_together={('file_path', 'sha256_hash')},
        ),
        migrations.AddField(
            model_name='codechange',
            name='new_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_to', to='api.codesnapshot'),
        ),
        migrations.AddField(
            model_name='codechange',
            name='old_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_from', to='api.codesnapshot'),
        ),
        migrations.AddIndex(
            model_name='codechange',
            index=models.Index(fields=['file_path', 'created_at'], name='api_codecha_file_pa_8af123_idx'),
        ),
        migrations.AddIndex(
            model_name='codechange',
            index=models.Index(fields=['source', 'created_at'], name='api_codecha_source_ec6a6c_idx'),
        ),
        migrations.AddIndex(
            model_name='codechange',
            index=models.Index(fields=['change_type'], name='api_codecha_change__b716ce_idx'),
        ),
        migrations.AddIndex(
            model_name='codechange',
            index=models.Index(fields=['session_id'], name='api_codecha_session_c9e619_idx'),
        ),
    ]
