# Generated by Django 5.2.9 on 2026-01-08 21:00

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_google_calendar_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='googlecalendarcredential',
            new_name='api_googlec_user_id_d2276a_idx',
            old_name='api_googleca_user_id_enabled_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduledtask',
            new_name='api_schedul_user_id_a5e46b_idx',
            old_name='api_schedul_user_id_status_scheduled_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduledtask',
            new_name='api_schedul_schedul_10307e_idx',
            old_name='api_schedul_scheduled_status_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduledtask',
            new_name='api_schedul_calenda_33be6c_idx',
            old_name='api_schedul_calendar_event_id_idx',
        ),
        migrations.AlterField(
            model_name='googlecalendarcredential',
            name='client_secret',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='googlecalendarcredential',
            name='refresh_token',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='googlecalendarcredential',
            name='token',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
    ]
