# Generated by Django 5.2.9 on 2026-01-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_api_googleca_user_id_enabled_idx_api_googlec_user_id_d2276a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccountLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_user_id', models.CharField(max_length=128)),
                ('auth0_user_id', models.CharField(max_length=255)),
                ('linked_by', models.CharField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['local_user_id'], name='api_useracc_local_u_7da4e6_idx'), models.Index(fields=['auth0_user_id'], name='api_useracc_auth0_u_99fe27_idx'), models.Index(fields=['verified'], name='api_useracc_verifie_165a3b_idx')],
                'unique_together': {('local_user_id', 'auth0_user_id')},
            },
        ),
    ]
